const BASE = 'https://nummai.com';

export async function GET() {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Terms of Service – Nummy</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f7f9f5;
      color: #1a1a1a;
    }
    nav {
      background: #fff;
      border-bottom: 1px solid #e8ede6;
      padding: 14px 32px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    nav img { width: 32px; height: 32px; border-radius: 8px; }
    nav .brand { font-weight: 700; font-size: 1.1rem; color: #2e5c27; flex: 1; }
    nav a { color: #4f7942; text-decoration: none; font-size: 0.9rem; margin-left: 20px; }
    nav a:hover { text-decoration: underline; }
    .content {
      max-width: 720px;
      margin: 48px auto;
      padding: 0 24px 80px;
    }
    .page-header {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 8px;
    }
    .page-header img { width: 52px; height: 52px; border-radius: 12px; }
    h1 { font-size: 2rem; color: #2e5c27; font-weight: 800; }
    .updated { color: #888; font-size: 0.9rem; margin-bottom: 40px; margin-top: 4px; }
    h2 { font-size: 1.1rem; font-weight: 700; color: #2e5c27; margin-top: 36px; margin-bottom: 10px; }
    p { font-size: 1rem; color: #333; line-height: 1.7; margin-bottom: 12px; }
    ul { padding-left: 20px; margin-bottom: 12px; }
    li { font-size: 1rem; color: #333; line-height: 1.7; margin-bottom: 4px; }
    a { color: #4f7942; }
    footer {
      background: #fff;
      border-top: 1px solid #e8ede6;
      padding: 24px 32px;
      text-align: center;
      font-size: 0.85rem;
      color: #888;
    }
    footer a { color: #4f7942; text-decoration: none; margin: 0 10px; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <nav>
    <img src="${BASE}/icon" alt="Nummy logo" />
    <span class="brand">Nummy</span>
    <a href="${BASE}/home">Home</a>
    <a href="${BASE}/privacy">Privacy Policy</a>
  </nav>

  <div class="content">
    <div class="page-header">
      <img src="${BASE}/icon" alt="Nummy icon" />
      <h1>Terms of Service</h1>
    </div>
    <p class="updated">Last updated: March 21, 2026</p>

    <p>By downloading or using Nummy ("the App"), you agree to these Terms of Service. Please read them carefully.</p>

    <h2>1. Use of the App</h2>
    <p>Nummy is a personal meal planning app. You may use it for personal, non-commercial purposes. You agree not to misuse the App, attempt to access it in unauthorized ways, or use it in any manner that violates applicable laws.</p>

    <h2>2. Account Responsibility</h2>
    <p>You are responsible for maintaining the security of your account credentials. You agree to notify us immediately at <a href="mailto:nummyaimealplanning@gmail.com">nummyaimealplanning@gmail.com</a> if you suspect unauthorized access to your account.</p>

    <h2>3. AI-Generated Content</h2>
    <p>Meal plans, recipes, and nutritional information generated by Nummy are produced by AI and are intended for general informational purposes only. They are not a substitute for professional medical or nutritional advice. Always consult a qualified healthcare provider regarding dietary decisions, especially if you have health conditions or allergies.</p>
    <p>While we strive for accuracy, AI-generated content may occasionally contain errors. We are not responsible for outcomes resulting from reliance on AI-generated meal plans or recipes.</p>

    <h2>4. Google Calendar Integration</h2>
    <p>If you connect your Google Calendar, you authorize Nummy to create and manage meal plan events on your behalf. You can revoke this access at any time from your <a href="https://myaccount.google.com/permissions" target="_blank">Google Account permissions page</a>.</p>

    <h2>5. Intellectual Property</h2>
    <p>The Nummy app, including its design, branding, and original content, is owned by us. You retain ownership of any custom recipes you create within the app. You grant us a limited license to store and process your content to provide the service.</p>

    <h2>6. Termination</h2>
    <p>You may stop using the App and delete your account at any time from the Profile screen. We reserve the right to suspend or terminate accounts that violate these terms.</p>

    <h2>7. Disclaimers and Limitation of Liability</h2>
    <p>The App is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the App.</p>

    <h2>8. Changes to These Terms</h2>
    <p>We may update these terms from time to time. Continued use of the App after changes are posted constitutes your acceptance of the updated terms.</p>

    <h2>9. Governing Law</h2>
    <p>These terms are governed by the laws of the United States. Any disputes will be resolved in the courts of competent jurisdiction.</p>

    <h2>10. Contact</h2>
    <p>Questions about these terms? Email us at <a href="mailto:nummyaimealplanning@gmail.com">nummyaimealplanning@gmail.com</a>.</p>
  </div>

  <footer>
    <p>© ${new Date().getFullYear()} Nummy. All rights reserved.</p>
    <p style="margin-top: 8px;">
      <a href="${BASE}/home">Home</a>
      <a href="${BASE}/privacy">Privacy Policy</a>
      <a href="mailto:nummyaimealplanning@gmail.com">Contact</a>
    </p>
  </footer>
</body>
</html>`;

  return new Response(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}
